project8/app2/urls.py
from django.urls import path
from app2.views import *
app_name='mine'
urlpatterns=[
    path('hello/',hello,name='hello'),
]

project8/project8/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',hai,name='hai'),
    path('app2/',include('app2.urls')),
]

project8/app1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

project8/app2/views.py
from django.shortcuts import render

# Create your views here.
def hello(request):
    return render(request,'hello.html')

project8/templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is hai html page</h1>
        <h1><a href="{% url 'mine:hello' %}">click to display hai html page</a></h1>
    </center>
</body>
</html>

project8/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this hello page</h1>
        <h1><a href="{% url 'hai' %}">click to display hai html page</a></h1>
    </center>
</body>
</html>